import { use } from 'react';


import './globals.css'
import Navbar from './shared/Navbar'

// head
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head metadata={metadata}/>
      <body>
        <header>
          <Navbar/>
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  )
}
